-- Seed Chicago's 77 Community Areas as neighborhoods
-- This is a simplified version - in production, you'd want to load actual boundary polygons

INSERT INTO neighborhoods (name, slug, community_area_number) VALUES
('Rogers Park', 'rogers-park', 1),
('West Ridge', 'west-ridge', 2),
('Uptown', 'uptown', 3),
('Lincoln Square', 'lincoln-square', 4),
('North Center', 'north-center', 5),
('Lake View', 'lake-view', 6),
('Lincoln Park', 'lincoln-park', 7),
('Near North Side', 'near-north-side', 8),
('Edison Park', 'edison-park', 9),
('Norwood Park', 'norwood-park', 10),
('Jefferson Park', 'jefferson-park', 11),
('Forest Glen', 'forest-glen', 12),
('North Park', 'north-park', 13),
('Albany Park', 'albany-park', 14),
('Portage Park', 'portage-park', 15),
('Irving Park', 'irving-park', 16),
('Dunning', 'dunning', 17),
('Montclare', 'montclare', 18),
('Belmont Cragin', 'belmont-cragin', 19),
('Hermosa', 'hermosa', 20),
('Avondale', 'avondale', 21),
('Logan Square', 'logan-square', 22),
('Humboldt Park', 'humboldt-park', 23),
('West Town', 'west-town', 24),
('Austin', 'austin', 25),
('West Garfield Park', 'west-garfield-park', 26),
('East Garfield Park', 'east-garfield-park', 27),
('Near West Side', 'near-west-side', 28),
('North Lawndale', 'north-lawndale', 29),
('South Lawndale', 'south-lawndale', 30),
('Lower West Side', 'lower-west-side', 31),
('Loop', 'loop', 32),
('Near South Side', 'near-south-side', 33),
('Armour Square', 'armour-square', 34),
('Douglas', 'douglas', 35),
('Oakland', 'oakland', 36),
('Fuller Park', 'fuller-park', 37),
('Grand Boulevard', 'grand-boulevard', 38),
('Kenwood', 'kenwood', 39),
('Washington Park', 'washington-park', 40),
('Hyde Park', 'hyde-park', 41),
('Woodlawn', 'woodlawn', 42),
('South Shore', 'south-shore', 43),
('Chatham', 'chatham', 44),
('Avalon Park', 'avalon-park', 45),
('South Chicago', 'south-chicago', 46),
('South Deering', 'south-deering', 47),
('East Side', 'east-side', 48),
('West Pullman', 'west-pullman', 49),
('Riverdale', 'riverdale', 50),
('Hegewisch', 'hegewisch', 51),
('Garfield Ridge', 'garfield-ridge', 52),
('Archer Heights', 'archer-heights', 53),
('Brighton Park', 'brighton-park', 54),
('McKinley Park', 'mckinley-park', 55),
('Bridgeport', 'bridgeport', 56),
('New City', 'new-city', 57),
('West Elsdon', 'west-elsdon', 58),
('Gage Park', 'gage-park', 59),
('Clearing', 'clearing', 60),
('West Lawn', 'west-lawn', 61),
('Chicago Lawn', 'chicago-lawn', 62),
('West Englewood', 'west-englewood', 63),
('Englewood', 'englewood', 64),
('Greater Grand Crossing', 'greater-grand-crossing', 65),
('Ashburn', 'ashburn', 66),
('Auburn Gresham', 'auburn-gresham', 67),
('Beverly', 'beverly', 68),
('Washington Heights', 'washington-heights', 69),
('Mount Greenwood', 'mount-greenwood', 70),
('Morgan Park', 'morgan-park', 71),
('O''Hare', 'ohare', 72),
('Edgewater', 'edgewater', 73)
ON CONFLICT (slug) DO NOTHING;



